### ISSUE TITLE
Menu button to big

### ISSUE THREAD

**Issue by charlottanpottan** [charlottanpottan/Fylgja2019#12]
Jag har försökt att göra den mindre men inte hittat var. Jag skulle vilja att den var ungefär halva storleken från nu. /C

**Comment by piot** [comment]
The menu button is in the `OpenMainMenuButton` in the `PlayerInteraction` prefab. I made it half the size (50% width, 50% height).

![menu_button_layout](https://user-images.githubusercontent.com/544158/103533143-dfad5a00-4e8c-11eb-88c6-9f07dd7ab649.png)

Example on PC:
![menu_button_half_size](https://user-images.githubusercontent.com/544158/103533213-010e4600-4e8d-11eb-9195-ced162f7680c.png)
