### ISSUE TITLE
Render subtitles on top of movies

### ISSUE THREAD

**Issue by piot** [charlottanpottan/Fylgja2019#4]
We first render the frames of the movie to a texture using the VideoPlayer.

Then we are rendering that texture using Unitys GUI system with [DrawTexture](https://docs.unity3d.com/2018.4/Documentation/ScriptReference/Graphics.DrawTexture.html):

https://github.com/charlottanpottan/Fylgja2019/blob/b706476d6157459cdc67cd4c90b3fa90ad9884c9/Assets/Fylgja/Scripts/Movie/MoviePlayer.cs#L30

And basically nothing can be rendered *after* the GUI, as talked about here: [Unity Forum](https://forum.unity.com/threads/canvas-gui-drawtexture.284091/)

One thing to test if it works by using the normal canvas.

**Comment by piot** [comment]
Seems to be working with Render Mode: `Camera Near Plane`. Now we only need to good way to hide the minimap and other things :smile: 

![subtitles_on_top_of_camera_near_plane](https://user-images.githubusercontent.com/544158/101891752-bdccfa00-3ba2-11eb-8893-8821d37184b1.png)

**Comment by charlottanpottan** [comment]
Toppen!
